name: CI

on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx
    env:
      buildDir: "${{ github.workspace }}/build/${{ matrix.os }}/"

    steps:
      - uses: actions/checkout@v2
      - name: Get CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies with vcpkg
        uses: lukka/run-vcpkg@main
        with:
          vcpkgArguments: zlib liblzma pybind11
          vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
          vcpkgTriplet: ${{ matrix.triplet }}
          vcpkgGitCommitId: 5568f110b509a9fd90711978a7cb76bae75bb092

      - name: Build with CMake
        uses: lukka/run-cmake@main
        with:
          useVcpkgToolchainFile: true
          buildWithCMake: true
          buildDirectory: ${{ env.buildDir }}
